### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mrgprasad** [mkuehbach/SCORE#2]
Dear Dr. Kühbach,
Thank you for developing SCORE for performing microstructure transformation simulations. I followed the installation procedure described in the documentation but I got the following error message during compilation - 

![scoreError](https://user-images.githubusercontent.com/26977833/109648221-aa567d00-7b5a-11eb-8df2-d417be55db9d.png)

Since I am new to using SCORE, I don't understand this error message. I would appreciate your help in rectifying the problem?

Best regards,
Mahesh Prasad

**Comment by mrgprasad** [comment]
I was able to solve this problem. For future reference, if someone stumbles on this error, it is caused by GCC compiler. By adding (typedef long long __int64;) in the SCORE_Kernel.h file, the error is rectified.

**Comment by mrgprasad** [comment]
With continued installation, I got the following error -
![compilationError](https://user-images.githubusercontent.com/26977833/109661046-d88f8900-7b69-11eb-8a71-46ce461a87ef.png)
After a quick Google search I found that it is related to linking of szip library with HDF5, but how does one do this linking?
Could you please explain this ?

**Comment by mkuehbach** [comment]
Dear Mahesh,


Great that you took on this one. Right these ones where missing defines, the last one is that in the CMakeLists.txt for the section
linker with HDF5 it seems that you need to link with the szip and zlib libraries, that is add libz.a and libsz.a and that should be it.

When I used this code I always worked with the intel compiler. Make sure to check  http://doi.org/10.1088/1361-651X/ab51bd

The code from my PhD with the statistical ensemble things is the one here on this SCORE github.

The one from the DOI above is a more up-to-date code but this code has the statistical ensemble simulations deactivated
Instead, this code is meant to be used for large single RVEs, maximum RVE size is 1600^3 voxel.

The DOI above also gives a good overview of possibilities and limitations.

The supplementary material to the above DOI is on Zenodo. In there are also configuration files
to support with how to use SCORE.


All the best,

Markus

________________________________

**Comment by mrgprasad** [comment]
Thank you for the hint, the code compiles successfully now! 

Actually, your paper (10.1088/1361-651X/ab51bd) is the reason I am installing SCORE. I would like to perform simulations similar to the one described in the paper. I will use the code from Zenodo based on your suggestion.

Regards,
Mahesh Prasad

**Comment by mkuehbach** [comment]
Dear Mahesh,

Great to hear that you are interested in this one.
Yes, give it a run. I would be happy to hear your feedback.


Kind regards,
Markus

________________________________
